# Generated by Django 2.1.7 on 2019-04-03 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20190326_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=300)),
                ('company_website', models.CharField(default='', max_length=100)),
                ('company_phoneNo', models.TextField()),
                ('company_address', models.CharField(max_length=150)),
                ('company_city', models.CharField(max_length=150)),
                ('company_state', models.CharField(max_length=150)),
                ('company_country', models.CharField(max_length=150)),
                ('industry_list', models.CharField(choices=[(1, 'Account'), (2, 'IT sales'), (3, 'Health care')], max_length=10)),           
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
        ),
    ]
